web/router.ex
defmodule Discovery.Router do
  use Discovery.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discovery.Auth, repo: Discovery.Repo
  end

  scope "/", Discovery do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/chat", PageController, :chat_view
    # Sessions is our login controller:o
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Unauthenticated user actions
  scope "/users", Discovery do
    pipe_through [:browser]

    # Password Reset
    get "/reset", UserController, :reset
    post "/reset", EmailController, :reset
    get "/reset/:auth_id", UserController, :new_password
    post "/reset/update", UserController, :update_password
    put "/reset/update", UserController, :update_password
  end

  scope "/users", Discovery do
    pipe_through [:browser, :authenticated_not_allowed]
    # Create a user
    get "/new", UserController, :new_redirect # Graceful fallback
    get "/new/:unique_company_id", UserController, :new_redirect # Graceful fallback
    get "/new/:unique_company_id/:token", UserController, :new
    post "/", UserController, :create
  end

  # Added scope to the routes for the authentication middleware
  scope "/users", Discovery do
    pipe_through [:browser, :authenticate_user]
    # Lock down the other User functions that should be behind authentication
    resources "/", UserController, except: [:new, :create]
  end
  
  # Companies router + middleware
  scope "/companies", Discovery do
    pipe_through [:browser, :authenticate_user]
    # get "/join", CompanyController, :join
    get "/join", CompanyController, :join_company
    get "/github_link", CompanyController, :github_link
    resources "/", CompanyController, except: [:join, :github_link]
  end

# Random Authenticated Routes
scope "/", Discovery do
  pipe_through [:browser, :authenticate_user]

  post "/invite/:company", EmailController, :invite # Sends email for invitation
end
  
  # Tickets router + middleware
  scope "/tickets", Discovery do
    pipe_through [:browser, :authenticate_user]
    get "/:id/export", TicketController, :export
    get "/:id/github_export", TicketController, :github_export
    resources "/", TicketController, except: [:export, :github_export]
  end
end

web/models/user.ex
defmodule Discovery.User do
  use Discovery.Web, :model

  alias Discovery.Company
  alias Discovery.Ticket
  
  schema "users" do
    field :first_name, :string
    field :last_name, :string
    field :email, :string, unique: true
    field :password, :string, virtual: true
    field :password_hash, :string
    field :role, :string
    field :auth_id, :string
    
    belongs_to :company, Company
    has_many :tickets, Ticket
    
    timestamps
  end

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, ~w(first_name last_name role), ~w(auth_id))
    |> validate_length(:first_name, min: 1)
    |> validate_length(:last_name, min: 1)
    |> validate_inclusion(:role, ["User", "Owner", "Admin"])
    |> email_changeset(params)
  end

  def email_changeset(model, params) do
    model
    |> cast(params, ~w(email), [])
    |> validate_length(:email, min: 1)
    |> validate_format(:email, ~r/@/) # Checks for @ sign in email
    |> update_change(:email, &String.downcase/1) # Normalize all emails
    |> unique_constraint(:email)
  end

  def password_changeset(model, params) do
    model
    |> cast(params, ~w(password), []) 
    |> validate_length(:password, min: 8)
    |> validate_format(:password, ~r/[a-z]/)
    |> validate_format(:password, ~r/[A-Z]/)
    |> validate_format(:password, ~r/[0-9]/)
    |> validate_format(:password, ~r/[!@#$%^&+=]/)
  end

  def registration_changeset(model, params) do
    model
    |> changeset(params)
    |> password_changeset(params)
    |> put_pass_hash()
  end

  def update_changeset(model, params) do
    cond do
      Map.has_key?(params, :password) -> 
        case params[:password] do
          "" -> 
            model
            |> changeset(params)
          _ -> 
            model
            |> password_changeset(params)
        end
      Map.has_key?(params, "password") -> 
        case params["password"] do
          "" -> 
            model
            |> changeset(params)
          _ -> 
            model
            |> password_changeset(params)
          end
      true ->
        :ok
    end
  end

  def update_owner_changeset(model, params) do
     model
     |> cast(params, ~w(role), [])
  end

  def reset_password_changeset(model, params \\ :empty) do
    model
    |> password_changeset(params)
    |> put_pass_hash()
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
      _ ->
        changeset
    end
  end
end

web/controllers/user_controller.ex
defmodule Discovery.UserController do
  use Discovery.Web, :controller

  alias Discovery.User
  alias Discovery.Company

  plug :authenticate_user when action in [:index, :show]
  plug :access_user when action in [:edit, :update, :delete]
  # scrub params checks for empty params when submitting forms
  # unfortunately, this means that when we update a user(leaving password blank)
  # the changeset is rendered invalid
  # plug :scrub_params, "user" when action in [:create, :update]

  def index(conn, _params) do
    users = 
    Repo.all(User)
    |> Repo.preload(:company)
    
    render conn, "index.html", users: users
  end

  def new(conn, %{"unique_company_id" => unique_company_id}) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", unique_company_id: unique_company_id, changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    # User is already in DB from invitation - Find them
    user = Repo.get_by!(User, email: user_params["email"])
    # Get the registration changeset from that user and cast the params submitted
    changeset = User.registration_changeset(user, user_params)
    |> Ecto.Changeset.put_change(:auth_id, "")

    company = Repo.get_by!(Company, unique_id: user_params["unique_company_id"])

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> Discovery.Auth.login(user)
        |> put_flash(:info, "Welcome #{user.first_name} #{user.last_name}!")
        |> redirect(to: company_path(conn, :join_company, company: company))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, unique_company_id: user_params["unique_company_id"])
    end
  end

  def show(conn, %{"id" => id}) do
    user = 
    Repo.get!(User, id)
    |> Repo.preload(:company)
    # We found a user with a company and want to return the company name to the template
    company = Repo.get_by!(Discovery.Company, id: user.company_id)
    conn 
      |> assign(:company, company)
      |> render("show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    currentUser = Repo.get!(User, conn.assigns.current_user.id)
    render(conn, "edit.html", user: user, changeset: changeset, currentUser: currentUser)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    # If the user is going to assign a new owner, change their current role to an admin
    if user_params["role"] == "Owner" do
      if change_owner(conn) == {:error, conn} do
        conn
         |> put_flash(:error, "Error Updating User")
         |> redirect(to: user_path(conn, :index))
         |> halt()
      end
    end
    changeset = User.update_changeset(user, user_params)
    case Repo.update(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    tickets = Repo.all(assoc(user, :tickets))
    case length(tickets) do
      0 ->
        Repo.delete!(user)
        conn
        |> put_flash(:info, "User deleted successfully.")
        |> redirect(to: user_path(conn, :index))
      _ ->
        conn
         |> put_flash(:error, "Please re-assign all tickets from this user before deleting")
         |> redirect(to: user_path(conn, :index)) #TODO: Change this to go to where all the tickets are
         |> halt()
    end
  end

  def reset(conn, _params) do
    render(conn, "reset.html")
  end

  def new_password(conn, %{"auth_id" => auth_id}) do
    changeset = User.update_changeset(%User{}, %{password: ""})
    render(conn, "update.html", auth_id: auth_id, changeset: changeset)
  end

  # This is from the reset password flow
  def update_password(conn, %{"update_form" => update_params}) do
    # find user by auth_id
    user = Repo.get_by(User, auth_id: update_params["auth_id"])
    case user do
      nil ->
        conn
        |> put_flash(:error, "Unauthorized attempt to change a password. Please try going through the reset password flow again.")
        |> redirect(to: user_path(conn, :reset))
        |> halt()
      _ ->
        # Pass the password to the password_changeset
        changeset = User.reset_password_changeset(user, update_params)
        #update the user with the new password
        case Repo.update(changeset) do
          {:ok, user} ->
            # Remove the auth_id
            Repo.update(Ecto.Changeset.change(changeset, auth_id: ""))
            conn
            |> put_flash(:info, "Password updated successfully.")
            |> redirect(to: ticket_path(conn, :index))
          {:error, changeset} ->
            render(conn, "update.html", auth_id: update_params["auth_id"], changeset: changeset)
        end
    end
  end

  #Plug used to determine if the user has access to do an action within the User model space
  def access_user(conn, _options) do
    otherUser = Repo.get!(User, conn.params["id"])
    if to_string(conn.assigns.current_user.id) == conn.params["id"] or conn.assigns.current_user.role == "Owner" or (conn.assigns.current_user.role == "Admin" and otherUser.role != "Owner")  do
      conn
    else
       conn
         |> put_flash(:error, "Error, You do not have access do this")
         |> redirect(to: user_path(conn, :index))
         |> halt()   
    end
  end

  def change_owner(conn) do
    this_user = Repo.get!(User, conn.assigns.current_user.id)
    this_user_params = %{"role" => "Admin"}
    changeset = User.update_owner_changeset(this_user, this_user_params)
    case Repo.update(changeset) do
      {:ok, user} -> {:ok, user}
      {:error, changeset} -> {:error, conn}
    end
  end
  # redirects any user who didnt get the email and may have accidentally got to this url
  def new_redirect(conn, _params) do
    conn
    |> put_flash(:error, "You must be invited before you can create an account. Please contact support or your organizational leader for help.")
    |> redirect(to: page_path(conn, :index))
  end
end

web/views/user_view.ex
defmodule Discovery.UserView do
  use Discovery.Web, :view
end

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user), unique_company_id: "" %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :first_name, class: "control-label" %>
    <%= text_input f, :first_name, class: "form-control" %>
    <%= error_tag f, :first_name %>
  </div>

  <div class="form-group">
    <%= label f, :last_name, class: "control-label" %>
    <%= text_input f, :last_name, class: "form-control" %>
    <%= error_tag f, :last_name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control password" %>
    <%= error_tag f, :password %>
    <ul class="helper-text">
      <li class="length">Must be at least 8 characters long.</li>
      <li class="lowercase">Must contain a lowercase letter.</li>
      <li class="uppercase">Must contain an uppercase letter.</li>
      <li class="special">Must contain a number or special character.</li>
    </ul>
  </div>

  <div class="form-group">
    <%= if assigns[:currentUser] do %>
      <%= if @currentUser.role == "Owner" do %>
        <%= label f, :role, class: "control-label" %>
        <%= select f, :role, ["User","Admin","Owner"], class: "form-control" %>
        <%= error_tag f, :role %>      
      <% end %>
      <%= if @currentUser.role  == "Admin" do %>
        <%= label f, :role, class: "control-label" %>
        <%= select f, :role, ["User","Admin"], class: "form-control" %>
        <%= error_tag f, :role %>      
      <% end %>
    <%= else %>
        <%= label f, :role, class: "control-label" %>
        <%= select f, :role, ["User","Admin","Owner"], class: "form-control" %>
        <%= error_tag f, :role %>
    <%= end %>
  </div>

  <%= hidden_input f, :unique_company_id, value: @unique_company_id %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Role</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      
      <td>
      <%= if user.company do %>
        <%= user.company.name %>
      <% end %>
      </td>
      <td><%= user.role %></td>

      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/user/new.html.eex
<h2>Get Registered!</h2>

<%= render "form.html", changeset: @changeset, unique_company_id: @unique_company_id,
                        action: user_path(@conn, :create) %>

<%= link "Login", to: session_path(@conn, :new) %>

web/templates/user/reset.html.eex
<h2>Reset Password</h2>

<p>Please enter your email address to reset your password</p>
<%= form_for @conn, email_path(@conn, :reset), [as: :reset_form], fn f -> %>
	<div class="form-group">
		<label>
			Email: <%= email_input f, :email, placeholder: "Email" %>
		</label>
	</div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/show.html.eex
<h2>Show user</h2>

<ul>

  <li>
    <strong>First name:</strong>
    <%= @user.first_name %>
  </li>

  <li>
    <strong>Last name:</strong>
    <%= @user.last_name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Password_hash:</strong>
    <%= @user.password_hash %>
  </li>

  <li>
    <strong>Company:</strong>
    <%= if @user.company do %>
      <%= link "#{@company.name}", to: company_path(@conn, :show, @company.id) %>
    <% end %>
  </li>
  <li>
    <strong>Role: </strong>
    <%= @user.role %>
  </li>
</ul>

<%= link "Edit", to: user_path(@conn, :edit, @user) %>
<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/update.html.eex
<h2>Update Password</h2>

<p>Please enter your new password</p>
<%= form_for @changeset, user_path(@conn, :update_password), [as: :update_form], fn f -> %>
  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control", id: "user_password" %>
    <%= error_tag f, :password %>
    <ul class="helper-text">
      <li class="length">Must be at least 8 characters long.</li>
      <li class="lowercase">Must contain a lowercase letter.</li>
      <li class="uppercase">Must contain an uppercase letter.</li>
      <li class="special">Must contain a number or special character.</li>
    </ul>
  </div>
  <%= hidden_input f, :auth_id, value: @auth_id %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>