web/router.ex
defmodule Discovery.Router do
  use Discovery.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discovery.Auth, repo: Discovery.Repo
  end

  scope "/", Discovery do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/chat", PageController, :chat_view
    # Sessions is our login controller:o
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Unauthenticated user actions
  scope "/users", Discovery do
    pipe_through [:browser]

    # Password Reset
    get "/reset", UserController, :reset
    post "/reset", EmailController, :reset
    get "/reset/:auth_id", UserController, :new_password
    post "/reset/update", UserController, :update_password
    put "/reset/update", UserController, :update_password
  end

  scope "/users", Discovery do
    pipe_through [:browser, :authenticated_not_allowed]
    # Create a user
    get "/new", UserController, :new_redirect # Graceful fallback
    get "/new/:unique_company_id", UserController, :new_redirect # Graceful fallback
    get "/new/:unique_company_id/:token", UserController, :new
    post "/", UserController, :create
  end

  # Added scope to the routes for the authentication middleware
  scope "/users", Discovery do
    pipe_through [:browser, :authenticate_user]
    # Lock down the other User functions that should be behind authentication
    resources "/", UserController, except: [:new, :create]
  end
  
  # Companies router + middleware
  scope "/companies", Discovery do
    pipe_through [:browser, :authenticate_user]
    # get "/join", CompanyController, :join
    get "/join", CompanyController, :join_company
    get "/github_link", CompanyController, :github_link
    resources "/", CompanyController, except: [:join, :github_link]
  end

# Random Authenticated Routes
scope "/", Discovery do
  pipe_through [:browser, :authenticate_user]

  post "/invite/:company", EmailController, :invite # Sends email for invitation
end
  
  # Tickets router + middleware
  scope "/tickets", Discovery do
    pipe_through [:browser, :authenticate_user]
    get "/:id/export", TicketController, :export
    get "/:id/github_export", TicketController, :github_export
    resources "/", TicketController, except: [:export, :github_export]
  end
end

web/views/layout_view.ex
defmodule Discovery.LayoutView do
  use Discovery.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discovery!</title>

    <%# Polymer things %>
    <script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-56399673-8', 'auto');
    ga('send', 'pageview');

  </script>
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ol class="breadcrumb text-right">
            <%= if @current_user do %>
              <li><%= link "My Account", to: user_path(@conn, :edit, @current_user) %></li>
              <li><%= link "Home", to: page_path(@conn, :index) %></li>
              <li><%= link "Users", to: user_path(@conn, :index) %></li>
              <li><%= link "Tickets", to: ticket_path(@conn, :index) %></li>
              <%= if @current_user.company_id do %>
                <li><%= link "Company", to: company_path(@conn, :show, @current_user.company_id) %></li>
              <% end %>
              <li><%= link "Log Out", to: session_path(@conn, :delete, @current_user), method: "delete" %></li>
            <% else %>
              <li><%= link "Log In", to: session_path(@conn, :new) %></li>
            <% end %>
          </ol>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>